(()=>{
 let selected=null,interaction=null;
 const announce=(type,data={})=>window.parent.postMessage({source:'useless-linkedin-editor',type,...data},window.location.origin);
 const number=(value,fallback=0)=>Number.isFinite(Number(value))?Number(value):fallback;
 const rgbToHex=value=>{const match=String(value).match(/rgba?\((\d+),\s*(\d+),\s*(\d+)/);return match?'#'+match.slice(1,4).map(x=>Number(x).toString(16).padStart(2,'0')).join(''):'#ffffff';};
 function details(){if(!selected)return null;const style=getComputedStyle(selected),rect=selected.getBoundingClientRect();return {tag:selected.tagName.toLowerCase(),classes:typeof selected.className==='string'?selected.className:'',text:selected.children.length?null:selected.textContent,x:number(selected.dataset.editorX),y:number(selected.dataset.editorY),width:Math.round(rect.width),height:Math.round(rect.height),fontSize:parseFloat(style.fontSize)||0,opacity:Math.round(Number(style.opacity)*100),color:rgbToHex(style.color),backgroundColor:rgbToHex(style.backgroundColor),image:selected.tagName==='IMG'};}
 function report(){announce('selection',{details:details()});}
 function moved(el,x,y){el.dataset.editorX=String(Math.round(x));el.dataset.editorY=String(Math.round(y));el.style.transform=`translate(${Math.round(x)}px, ${Math.round(y)}px)`;report();announce('dirty');}
 function select(el){if(selected===el)return;if(selected){selected.removeAttribute('data-editor-selected');interaction?.unset();}selected=el;interaction=null;if(!el){report();return;}el.setAttribute('data-editor-selected','true');interaction=interact(el).draggable({ignoreFrom:'[contenteditable="true"]',listeners:{move(event){moved(event.target,number(event.target.dataset.editorX)+event.dx,number(event.target.dataset.editorY)+event.dy);}}}).resizable({edges:{left:true,right:true,top:true,bottom:true},margin:7,ignoreFrom:'[contenteditable="true"]',listeners:{move(event){const target=event.target;target.style.width=`${Math.max(5,event.rect.width)}px`;target.style.height=`${Math.max(5,event.rect.height)}px`;target.style.boxSizing='border-box';moved(target,number(target.dataset.editorX)+event.deltaRect.left,number(target.dataset.editorY)+event.deltaRect.top);}}});report();}
 function eligible(el){return el instanceof HTMLElement&&el!==document.body&&el!==document.documentElement&&!['SCRIPT','STYLE','LINK'].includes(el.tagName)&&!el.matches('.page,.cv-container');}
 document.addEventListener('click',event=>{event.preventDefault();const el=event.target;if(eligible(el))select(el);},true);
 document.addEventListener('dblclick',event=>{const el=event.target;if(!eligible(el)||el.tagName==='IMG')return;event.preventDefault();select(el);el.contentEditable='true';el.setAttribute('data-editor-editing','true');el.focus();const end=()=>{el.contentEditable='false';el.removeAttribute('data-editor-editing');el.removeEventListener('blur',end);report();announce('dirty');};el.addEventListener('blur',end);},true);
 function set(key,value){if(!selected)return;const s=selected.style;if(key==='text'){if(selected.children.length)throw Error('Edit nested text directly on the page');selected.textContent=String(value);}else if(key==='x'||key==='y'){moved(selected,key==='x'?number(value):number(selected.dataset.editorX),key==='y'?number(value):number(selected.dataset.editorY));}else if(key==='width'||key==='height'){s[key]=`${Math.max(1,number(value,1))}px`;s.boxSizing='border-box';}else if(key==='fontSize'){s.fontSize=`${Math.max(1,number(value,1))}px`;}else if(key==='opacity'){s.opacity=String(Math.min(100,Math.max(0,number(value)))/100);}else if(key==='color'||key==='backgroundColor'){s[key]=String(value);}else if(key==='front'){s.zIndex='99';if(getComputedStyle(selected).position==='static')s.position='relative';}else if(key==='reset'){for(const name of ['transform','width','height','boxSizing','zIndex','position'])s[name]='';delete selected.dataset.editorX;delete selected.dataset.editorY;}else if(key==='image'){if(selected.tagName!=='IMG'||!/^data:image\/(?:png|jpeg|webp);base64,/.test(value))throw Error('Select an image file');selected.src=value;}else throw Error('Unknown property');report();announce('dirty');}
 function serialize(){const clone=document.documentElement.cloneNode(true);clone.querySelectorAll('[data-editor-runtime]').forEach(el=>el.remove());clone.querySelectorAll('[data-editor-selected],[data-editor-editing]').forEach(el=>{el.removeAttribute('data-editor-selected');el.removeAttribute('data-editor-editing');el.removeAttribute('contenteditable');});return '<!doctype html>\n'+clone.outerHTML;}
 window.editorApi={set,serialize,details};announce('ready');
})();
