const names={id:'记录 ID',date:'日期',company:'公司名称',role:'申请职位',match_level:'匹配度',jd:'完整 JD',mode:'投递模式',resume_path:'使用简历',letter_path:'动机信',applied:'已投递',awaiting_interview:'等待面试',awaiting_result:'等待结果',status:'执行状态',job_url:'岗位链接',requisition_id:'招聘编号',liveness:'有效性',duplicate_status:'重复状态',knockout:'Knock-out',channel:'投递渠道',next_action:'下一步',followup_date:'跟进日期',last_contact:'最近联系',notes:'卡点 / 结果',submission_evidence:'提交成功凭证'};
let selected=null,focus='',page=1,refreshSerial=0,closeTimer=null,enterFrame=null,dialogRevision=0,lastTrendSignature='';
const today=()=>{const d=new Date();return new Date(d.getTime()-d.getTimezoneOffset()*60000).toISOString().slice(0,10);};
const groups=[['申请与下一步',['id','date','company','role','status','next_action','followup_date','notes']],['岗位与匹配',['job_url','requisition_id','jd','match_level','liveness','duplicate_status','knockout']],['材料与投递',['mode','resume_path','letter_path','channel','applied','awaiting_interview','awaiting_result','submission_evidence','last_contact']]];
const $=s=>document.querySelector(s);
async function api(url,options){const response=await fetch(url,options);const data=await response.json();if(!response.ok)throw Error(data.error||'请求失败');return data;}
function el(tag,className,text){const node=document.createElement(tag);if(className)node.className=className;if(text!==undefined)node.textContent=text;return node;}
function stat(label,value,note,filter){const card=el('button','stat');card.type='button';card.dataset.focus=filter;card.setAttribute('aria-pressed',String(focus===filter));card.setAttribute('aria-label',`${label} ${value} 条，查看对应申请记录`);card.append(el('span','',label),el('strong','',String(value)),el('small','',note));return card;}
function svgNode(name,attributes={}){const node=document.createElementNS('http://www.w3.org/2000/svg',name);for(const [key,value] of Object.entries(attributes))node.setAttribute(key,String(value));return node;}
function renderTrend(points){
 const total=points.reduce((sum,item)=>sum+item.count,0),highest=Math.max(0,...points.map(item=>item.count));
 const step=highest<=4?1:Math.ceil(highest/3),peak=Math.max(1,Math.ceil(highest/step)*step);
 $('#trend-total').textContent=`${total} 条`;
 const chart=$('#trend-chart');chart.setAttribute('aria-label',`最近 ${points.length} 天标记已提交 ${total} 条，单日最多 ${highest} 条`);
 const svg=svgNode('svg',{viewBox:'0 0 1100 210',role:'group','aria-label':'每日投递数量；可用方向键逐个查看日期'});
 const defs=svgNode('defs'),gradient=svgNode('linearGradient',{id:'trend-fill',x1:'0',y1:'0',x2:'0',y2:'1'});
 gradient.append(svgNode('stop',{offset:'0%','stop-color':'#65a8f4','stop-opacity':'.28'}),svgNode('stop',{offset:'100%','stop-color':'#65a8f4','stop-opacity':'.01'}));defs.append(gradient);svg.append(defs);
 const left=48,right=1080,top=16,bottom=170;
 const y=count=>bottom-count/peak*(bottom-top),x=index=>left+index/Math.max(1,points.length-1)*(right-left);
 for(let count=0;count<=peak;count+=step){
  svg.append(svgNode('line',{x1:left,x2:right,y1:y(count),y2:y(count),class:'trend-gridline'}));
  const label=svgNode('text',{x:left-12,y:y(count)+4,class:'trend-tick','text-anchor':'end'});label.textContent=String(count);svg.append(label);
 }
 for(const index of [...new Set([0,5,10,15,points.length-1])]){
  if(!points[index])continue;
  const label=svgNode('text',{x:x(index),y:199,class:'trend-tick','text-anchor':index===0?'start':index===points.length-1?'end':'middle'});label.textContent=points[index].date.slice(5);svg.append(label);
 }
 if(!points.length){chart.replaceChildren(svg);chart.dataset.loading='false';return;}
 const line=points.map((item,index)=>`${index?'L':'M'}${x(index).toFixed(1)},${y(item.count).toFixed(1)}`).join(' ');
 const series=svgNode('g',{class:'trend-series'});
 series.append(svgNode('path',{d:`${line} L${x(points.length-1).toFixed(1)},${bottom} L${left},${bottom} Z`,class:'trend-area'}),svgNode('path',{d:line,class:'trend-line'}));
 const markers=points.map((item,index)=>{const point=svgNode('circle',{cx:x(index),cy:y(item.count),r:4,class:`trend-point${item.count?' has-count':''}`,tabindex:'0','aria-label':`${item.date}：${item.count} 条`});point.append(svgNode('title'));point.firstChild.textContent=`${item.date}：${item.count} 条`;point.addEventListener('focus',()=>showTip(index));point.addEventListener('blur',hideTip);point.addEventListener('keydown',event=>{if(!['ArrowLeft','ArrowRight'].includes(event.key))return;event.preventDefault();markers[Math.min(points.length-1,Math.max(0,index+(event.key==='ArrowRight'?1:-1)))].focus();});series.append(point);return point;});
 svg.append(series);
 const hitArea=svgNode('rect',{x:left,y:top,width:right-left,height:bottom-top,fill:'transparent',class:'trend-hit-area'});
 hitArea.addEventListener('pointermove',event=>{if(event.pointerType==='touch')return;const box=svg.getBoundingClientRect();const position=(event.clientX-box.left)/box.width*1100;showTip(Math.min(points.length-1,Math.max(0,Math.round((position-left)/(right-left)*(points.length-1)))));});
 hitArea.addEventListener('pointerleave',hideTip);svg.append(hitArea);
 const tooltip=el('div','trend-tooltip');tooltip.setAttribute('aria-hidden','true');let activeIndex=-1;
 chart.replaceChildren(svg,tooltip);chart.dataset.loading='false';
 function showTip(index){if(index===activeIndex&&chart.dataset.tooltip==='visible')return;activeIndex=index;const item=points[index],box=svg.getBoundingClientRect(),chartBox=chart.getBoundingClientRect();tooltip.textContent=`${item.date} · ${item.count} 条`;tooltip.style.left=`${Math.min(chartBox.width-72,Math.max(72,x(index)/1100*box.width+box.left-chartBox.left))}px`;tooltip.style.top=`${y(item.count)/210*box.height+box.top-chartBox.top}px`;chart.dataset.tooltip='visible';markers.forEach((marker,i)=>marker.classList.toggle('is-active',i===index));}
 function hideTip(){activeIndex=-1;chart.dataset.tooltip='';markers.forEach(marker=>marker.classList.remove('is-active'));}
}
function badge(record){const status=record.status;const css=status==='已提交'?'submitted':status==='受阻'||status==='待用户'?'blocked':status==='跳过'?'skipped':'';const wrapper=el('div','status-stack');wrapper.append(el('span',`badge ${css}`,status||'待处理'));if(status==='已提交'){const verified=record.submission_verified===1;const note=el('span',`receipt-note ${verified?'verified':'pending'}`,verified?'凭证已核验':'凭证待核验');const symbol=el('span','receipt-symbol',verified?'✓':'·');symbol.setAttribute('aria-hidden','true');note.prepend(symbol);wrapper.append(note);}return wrapper;}
function row(record){const tr=el('tr');const company=el('td');company.append(el('span','company',record.company),el('span','role',record.role),el('span','record-date',record.date));const state=el('td');state.append(badge(record));const match=el('td','muted',record.match_level||'—');const next=el('td','next-cell',record.next_action||'—');next.title=record.next_action||'';const due=record.followup_date&&record.followup_date<=today()&&!['跳过','拒绝','撤回','失效'].includes(record.status);const follow=el('td',`date-cell ${due?'due-date':'muted'}`,record.followup_date||'—');const action=el('td','action-cell');const button=el('button','linkbtn','查看');button.type='button';button.setAttribute('aria-label',`查看并编辑 ${record.company} · ${record.role}`);button.addEventListener('click',event=>edit(record.id,{animate:event.detail!==0}));action.append(button);tr.append(company,state,match,next,follow,action);return tr;}
async function refresh(){
 const serial=++refreshSerial;
 const params=new URLSearchParams({q:$('#search').value.trim(),status:$('#status').value,initial:$('#initial').value,sort:$('#sort').value,focus,page:String(page),pageSize:$('#page-size').value});
 try{
  const [sum,result,trend]=await Promise.all([api('/api/summary'),api(`/api/applications?${params}`),api('/api/trend')]);
  if(serial!==refreshSerial)return;
  $('#load-error').hidden=true;
  $('#stats').replaceChildren(stat('到期跟进',sum.followupDue,'查看需要联系的记录','due'),stat('待用户处理',sum.waitingUser,'等待确认或补充','waiting'),stat('提交待核验',sum.pendingVerification,'含尚未核验的旧记录','verify'),stat('已核验提交',sum.verifiedSubmitted,'查看已核验的申请','verified'));
  const trendSignature=JSON.stringify(trend);if(trendSignature!==lastTrendSignature){renderTrend(trend);lastTrendSignature=trendSignature;}
  for(const [id,value] of [['due-count',sum.followupDue],['waiting-count',sum.waitingUser],['verify-count',sum.pendingVerification],['verified-count',sum.verifiedSubmitted],['jd-count',sum.missingJd],['conflict-count',sum.stageConflicts]])$(`#${id}`).textContent=value;
  const rows=result.items;page=result.page;
  $('#rows').replaceChildren(...rows.map(row));
  const start=result.total?(page-1)*result.pageSize+1:0,end=start+rows.length-(result.total?1:0);
  $('#count').textContent=`${result.total} 条记录${result.total!==sum.total?` · 全部 ${sum.total} 条`:''}`;
  $('#page-info').textContent=`${start}–${end} / ${result.total} · 第 ${page} / ${result.pages} 页`;
  $('#page-prev').disabled=page<=1;$('#page-next').disabled=page>=result.pages;
  $('#empty').hidden=rows.length>0;
  const select=$('#status'),current=select.value;
  select.replaceChildren(new Option('全部状态',''),...Object.keys(sum.byStatus).sort().map(s=>new Option(`${s} (${sum.byStatus[s]})`,s)));
  select.value=current;
 }catch(error){if(serial===refreshSerial){$('#load-error').textContent=`加载失败：${error.message}`;$('#load-error').hidden=false;if(!lastTrendSignature){$('#trend-chart').dataset.loading='false';$('#trend-chart').replaceChildren(el('p','trend-error','每日投递数据暂时无法加载'));}$('#rows').replaceChildren();$('#empty').hidden=true;$('#count').textContent='加载失败';$('#page-info').textContent='';$('#page-prev').disabled=true;$('#page-next').disabled=true;}}
}
function control(key,value,isNew){const wrapper=el('label','field'+(['jd','notes','submission_evidence','next_action'].includes(key)?' full':''));wrapper.append(el('span','',names[key]));let input;if(['jd','notes','submission_evidence','next_action'].includes(key)){input=el('textarea');input.value=value||'';}else if(['applied','awaiting_interview','awaiting_result'].includes(key)){input=el('select');input.append(new Option('☐ 未勾选','☐'),new Option('☑ 已勾选','☑'));input.value=value||'☐';}else if(key==='status'){input=el('select');for(const s of ['待处理','待用户','材料已准备','投递中','待确认提交结果','已提交','跳过','受阻'])input.append(new Option(s,s));input.value=value||'待处理';}else{input=el('input');input.type=['date','followup_date','last_contact'].includes(key)?'date':key==='job_url'?'url':'text';input.value=value||'';}input.name=key;if(key==='id'&&!isNew)input.readOnly=true;if(['id','date','company','role'].includes(key))input.required=true;if(key==='jd')input.rows=6;wrapper.append(input);if(key==='submission_evidence')wrapper.append(el('small','field-hint','填写凭证不会自动计入“已核验提交”；需独立核验。'));if(key==='job_url'&&/^https?:\/\//i.test(value||'')){const link=el('a','','打开岗位页面 ↗');link.href=value;link.target='_blank';link.rel='noopener noreferrer';wrapper.append(link);}return wrapper;}
function show(record,{animate=true}={}){dialogRevision++;selected=record;const isNew=!record;$('#dialog-title').textContent=isNew?'新增申请记录':`${record.company} · ${record.role}`;const conflict=record&&[record.applied,record.awaiting_interview,record.awaiting_result].filter(x=>x==='☑').length>1?' · 此行阶段冲突，保存前请修正':'';$('#source').textContent=isNew?'新记录会保存到本地数据库':record.source_sheet?`来源：旧 Excel ${record.source_sheet} 第 ${record.source_row} 行 · 修改会保留事件记录${conflict}`:`修改会保留事件记录${conflict}`;const defaults={id:`UL-${today().replaceAll('-','')}-${crypto.randomUUID().slice(0,6)}`,date:today()};const sections=groups.map(([title,keys])=>{const section=el('section','form-section');section.append(el('h3','',title));const grid=el('div','section-grid');grid.append(...keys.map(key=>control(key,record?.[key]??defaults[key]??'',isNew)));section.append(grid);return section;});$('#form-fields').replaceChildren(...sections);$('#form-fields').scrollTop=0;$('#history').hidden=isNew;$('#history').open=false;$('#event-list').replaceChildren(...(isNew?[]:[el('li','','正在加载变更历史…')]));$('#form-error').textContent='';const dialog=$('#editor');dialog.scrollTop=0;clearTimeout(closeTimer);dialog.classList.remove('is-closing');if(!dialog.open){const useMotion=animate&&!matchMedia('(prefers-reduced-motion: reduce)').matches;if(useMotion)dialog.classList.add('is-entering');dialog.showModal();if(useMotion){void dialog.offsetWidth;enterFrame=requestAnimationFrame(()=>{dialog.classList.remove('is-entering');enterFrame=null;});}}return dialogRevision;}
function closeEditor({animate=false}={}){const dialog=$('#editor');if(!dialog.open)return;dialogRevision++;if(enterFrame!==null){cancelAnimationFrame(enterFrame);enterFrame=null;}dialog.classList.remove('is-entering');clearTimeout(closeTimer);if(!animate||matchMedia('(prefers-reduced-motion: reduce)').matches){dialog.close();dialog.classList.remove('is-closing');return;}dialog.classList.add('is-closing');closeTimer=setTimeout(()=>{dialog.close();dialog.classList.remove('is-closing');closeTimer=null;},180);}
async function edit(id,{animate=true}={}){let token=++dialogRevision;try{const record=await api(`/api/applications/${encodeURIComponent(id)}`);if(token!==dialogRevision)return;token=show(record,{animate});const events=await api(`/api/applications/${encodeURIComponent(id)}/events`);if(token!==dialogRevision||!$('#editor').open)return;const actionNames={'imported-from-excel':'从 Excel 导入','source-whitespace-restored':'恢复原文空白','submission-receipt-verified':'提交凭证已核验',created:'新建',updated:'修改'};$('#event-list').replaceChildren(...(events.length?events.map(x=>el('li','',`${new Date(x.at).toLocaleString('zh-CN')} · ${actionNames[x.action]||x.action}`)):[el('li','','暂无变更记录')]));}catch(e){if(token===dialogRevision)alert(e.message);}}
$('#record-form').addEventListener('submit',async event=>{event.preventDefault();const save=event.currentTarget.querySelector('button[type="submit"]');if(save.disabled)return;save.disabled=true;save.textContent='保存中…';let values=Object.fromEntries(new FormData(event.currentTarget).entries());try{const method=selected?'PATCH':'POST';const url=selected?`/api/applications/${encodeURIComponent(selected.id)}`:'/api/applications';if(selected){values=Object.fromEntries(Object.entries(values).filter(([key,value])=>value!==selected[key]));if(!Object.keys(values).length){closeEditor();return;}values.version=selected.version;}await api(url,{method,headers:{'Content-Type':'application/json'},body:JSON.stringify(values)});closeEditor();if(!selected)page=1;await refresh();}catch(e){$('#form-error').textContent=e.message;}finally{save.disabled=false;save.textContent='保存记录';}});
function setFocus(next,{clearFilters=false,scroll=false}={}){focus=next;page=1;if(clearFilters){$('#search').value='';$('#status').value='';$('#initial').value='';clearTimeout(timer);}for(const item of document.querySelectorAll('[data-focus]'))item.setAttribute('aria-pressed',String(item.dataset.focus===focus));refresh();if(scroll)$('.records').scrollIntoView({behavior:'auto',block:'start'});}
$('#focus-bar').addEventListener('click',event=>{const button=event.target.closest('button[data-focus]');if(button)setFocus(button.dataset.focus);});
$('#stats').addEventListener('click',event=>{const button=event.target.closest('button[data-focus]');if(button)setFocus(button.dataset.focus,{clearFilters:true,scroll:true});});
$('#reset-filters').addEventListener('click',()=>{$('#sort').value='date-desc';setFocus('',{clearFilters:true});$('#search').focus();});
$('#add').addEventListener('click',event=>show(null,{animate:event.detail!==0}));$('#close').addEventListener('click',event=>closeEditor({animate:event.detail!==0}));$('#cancel').addEventListener('click',event=>closeEditor({animate:event.detail!==0}));$('#editor').addEventListener('cancel',event=>{event.preventDefault();closeEditor();});const letters='ABCDEFGHIJKLMNOPQRSTUVWXYZ'.split('');$('#initial').append(...letters.map(letter=>new Option(letter,letter)),new Option('其他','#'));let timer;$('#search').addEventListener('input',()=>{clearTimeout(timer);page=1;timer=setTimeout(refresh,250);});for(const controlId of ['#status','#initial','#sort','#page-size'])$(controlId).addEventListener('change',()=>{page=1;refresh();});$('#page-prev').addEventListener('click',()=>{if(page>1){page--;refresh();}});$('#page-next').addEventListener('click',()=>{if(!$('#page-next').disabled){page++;refresh();}});refresh();
