const names={id:'记录 ID',date:'日期',company:'公司名称',role:'申请职位',match_level:'匹配度',jd:'完整 JD',mode:'投递模式',resume_path:'使用简历',letter_path:'动机信',applied:'已投递',awaiting_interview:'等待面试',awaiting_result:'等待结果',status:'执行状态',job_url:'岗位链接',requisition_id:'招聘编号',liveness:'有效性',duplicate_status:'重复状态',knockout:'Knock-out',channel:'投递渠道',next_action:'下一步',followup_date:'跟进日期',last_contact:'最近联系',notes:'卡点 / 结果',submission_evidence:'提交成功凭证'};
const fields=Object.keys(names);let selected=null,focus='',refreshSerial=0;
const today=()=>{const d=new Date();return new Date(d.getTime()-d.getTimezoneOffset()*60000).toISOString().slice(0,10);};
const groups=[['申请与下一步',['id','date','company','role','status','next_action','followup_date','notes']],['岗位与匹配',['job_url','requisition_id','jd','match_level','liveness','duplicate_status','knockout']],['材料与投递',['mode','resume_path','letter_path','channel','applied','awaiting_interview','awaiting_result','submission_evidence','last_contact']]];
const $=s=>document.querySelector(s);
async function api(url,options){const response=await fetch(url,options);const data=await response.json();if(!response.ok)throw Error(data.error||'请求失败');return data;}
function el(tag,className,text){const node=document.createElement(tag);if(className)node.className=className;if(text!==undefined)node.textContent=text;return node;}
function stat(label,value,note){const card=el('div','stat');card.append(el('span','',label),el('strong','',String(value)),el('small','',note));return card;}
function badge(record){const status=record.status;const css=status==='已提交'?'submitted':status==='受阻'||status==='待用户'?'blocked':status==='跳过'?'skipped':'';const wrapper=el('div','status-stack');wrapper.append(el('span',`badge ${css}`,status||'待处理'));if(status==='已提交')wrapper.append(el('small','',record.submission_verified===1?'✓ 凭证已核验':'凭证待核验'));return wrapper;}
function row(record){const tr=el('tr');const date=el('td','date-cell muted',record.date);const company=el('td');company.append(el('span','company',record.company),el('span','role',record.role));const state=el('td');state.append(badge(record));const match=el('td','muted',record.match_level||'—');const next=el('td','next-cell',record.next_action||'—');const due=record.followup_date&&record.followup_date<=today()&&!['跳过','拒绝','撤回','失效'].includes(record.status);const follow=el('td',`date-cell ${due?'due-date':'muted'}`,record.followup_date||'—');const action=el('td','action-cell');const button=el('button','linkbtn','查看 / 编辑');button.type='button';button.addEventListener('click',()=>edit(record.id));action.append(button);const cells=[date,company,state,match,next,follow,action];['日期','公司 / 岗位','状态','匹配度','下一步','跟进日期',''].forEach((label,i)=>{if(label)cells[i].dataset.label=label;});tr.append(...cells);return tr;}
async function refresh(){
 const serial=++refreshSerial;
 const params=new URLSearchParams({q:$('#search').value.trim(),status:$('#status').value,initial:$('#initial').value,sort:$('#sort').value,focus});
 try{
  const [sum,rows]=await Promise.all([api('/api/summary'),api(`/api/applications?${params}`)]);
  if(serial!==refreshSerial)return;
  $('#load-error').hidden=true;
  $('#stats').replaceChildren(stat('到期跟进',sum.followupDue,'查看需要联系的记录'),stat('待用户处理',sum.waitingUser,'等待确认或补充'),stat('提交待核验',sum.pendingVerification,'含尚未核验的旧记录'),stat('已核验提交',sum.verifiedSubmitted,`全部 ${sum.total} 条记录`));
  for(const [id,value] of [['due-count',sum.followupDue],['waiting-count',sum.waitingUser],['verify-count',sum.pendingVerification],['jd-count',sum.missingJd],['conflict-count',sum.stageConflicts]])$(`#${id}`).textContent=value;
  $('#rows').replaceChildren(...rows.map(row));
  $('#count').textContent=`显示 ${rows.length} / ${sum.total} 条记录${rows.length===1000?' · 达到显示上限，请缩小筛选范围':''}`;
  $('#empty').hidden=rows.length>0;
  const select=$('#status'),current=select.value;
  select.replaceChildren(new Option('全部状态',''),...Object.keys(sum.byStatus).sort().map(s=>new Option(`${s} (${sum.byStatus[s]})`,s)));
  select.value=current;
 }catch(error){if(serial===refreshSerial){$('#load-error').textContent=`加载失败：${error.message}`;$('#load-error').hidden=false;$('#rows').replaceChildren();$('#empty').hidden=true;$('#count').textContent='加载失败';}}
}
function control(key,value,isNew){const wrapper=el('label','field'+(['jd','notes','submission_evidence','next_action'].includes(key)?' full':''));wrapper.append(el('span','',names[key]));let input;if(['jd','notes','submission_evidence','next_action'].includes(key)){input=el('textarea');input.value=value||'';}else if(['applied','awaiting_interview','awaiting_result'].includes(key)){input=el('select');input.append(new Option('☐ 未勾选','☐'),new Option('☑ 已勾选','☑'));input.value=value||'☐';}else if(key==='status'){input=el('select');for(const s of ['待处理','待用户','材料已准备','投递中','待确认提交结果','已提交','跳过','受阻'])input.append(new Option(s,s));input.value=value||'待处理';}else{input=el('input');input.type=['date','followup_date','last_contact'].includes(key)?'date':key==='job_url'?'url':'text';input.value=value||'';}input.name=key;if(key==='id'&&!isNew)input.readOnly=true;if(['id','date','company','role'].includes(key))input.required=true;if(key==='jd')input.rows=6;wrapper.append(input);if(key==='submission_evidence')wrapper.append(el('small','field-hint','填写凭证不会自动计入“已核验提交”；需独立核验。'));if(key==='job_url'&&/^https?:\/\//i.test(value||'')){const link=el('a','','打开岗位页面 ↗');link.href=value;link.target='_blank';link.rel='noopener noreferrer';wrapper.append(link);}return wrapper;}
function show(record){selected=record;const isNew=!record;$('#dialog-title').textContent=isNew?'新增申请记录':`${record.company} · ${record.role}`;const conflict=record&&[record.applied,record.awaiting_interview,record.awaiting_result].filter(x=>x==='☑').length>1?' · 此行阶段冲突，保存前请修正':'';$('#source').textContent=record?.source_sheet?`来源：旧 Excel ${record.source_sheet} 第 ${record.source_row} 行 · 修改会保留事件记录${conflict}`:'新记录会保存到本地数据库';const defaults={id:`UL-${today().replaceAll('-','')}-${crypto.randomUUID().slice(0,6)}`,date:today()};const sections=groups.map(([title,keys])=>{const section=el('section','form-section');section.append(el('h3','',title));const grid=el('div','section-grid');grid.append(...keys.map(key=>control(key,record?.[key]??defaults[key]??'',isNew)));section.append(grid);return section;});$('#form-fields').replaceChildren(...sections);$('#history').hidden=isNew;$('#history').open=false;$('#event-list').replaceChildren();$('#form-error').textContent='';$('#editor').showModal();}
async function edit(id){try{const record=await api(`/api/applications/${encodeURIComponent(id)}`);show(record);const events=await api(`/api/applications/${encodeURIComponent(id)}/events`);const actionNames={'imported-from-excel':'从 Excel 导入','source-whitespace-restored':'恢复原文空白','submission-receipt-verified':'提交凭证已核验',created:'新建',updated:'修改'};$('#event-list').replaceChildren(...events.map(x=>el('li','',`${new Date(x.at).toLocaleString('zh-CN')} · ${actionNames[x.action]||x.action}`)));}catch(e){alert(e.message);}}
$('#record-form').addEventListener('submit',async event=>{event.preventDefault();const save=event.currentTarget.querySelector('button[type="submit"]');if(save.disabled)return;save.disabled=true;save.textContent='保存中…';let values=Object.fromEntries(new FormData(event.currentTarget).entries());try{const method=selected?'PATCH':'POST';const url=selected?`/api/applications/${encodeURIComponent(selected.id)}`:'/api/applications';if(selected){values=Object.fromEntries(Object.entries(values).filter(([key,value])=>value!==selected[key]));if(!Object.keys(values).length){$('#editor').close();return;}values.version=selected.version;}await api(url,{method,headers:{'Content-Type':'application/json'},body:JSON.stringify(values)});$('#editor').close();await refresh();}catch(e){$('#form-error').textContent=e.message;}finally{save.disabled=false;save.textContent='保存记录';}});
$('#focus-bar').addEventListener('click',event=>{const button=event.target.closest('button[data-focus]');if(!button)return;focus=button.dataset.focus;for(const item of $('#focus-bar').querySelectorAll('button'))item.setAttribute('aria-pressed',String(item===button));refresh();});
$('#reset-filters').addEventListener('click',()=>{$('#search').value='';$('#status').value='';$('#initial').value='';$('#sort').value='date-desc';focus='';for(const item of $('#focus-bar').querySelectorAll('button'))item.setAttribute('aria-pressed',String(item.dataset.focus===''));refresh();$('#search').focus();});
$('#add').addEventListener('click',()=>show(null));$('#close').addEventListener('click',()=>$('#editor').close());$('#cancel').addEventListener('click',()=>$('#editor').close());const letters='ABCDEFGHIJKLMNOPQRSTUVWXYZ'.split('');$('#initial').append(...letters.map(letter=>new Option(letter,letter)),new Option('其他','#'));let timer;$('#search').addEventListener('input',()=>{clearTimeout(timer);timer=setTimeout(refresh,250);});for(const controlId of ['#status','#initial','#sort'])$(controlId).addEventListener('change',refresh);refresh();
