import fs from 'node:fs/promises';
import path from 'node:path';
import {spawnSync} from 'node:child_process';
import {DatabaseSync} from 'node:sqlite';
import {root,args} from './runtime.mjs';
import {home,read,write,normalizeUrl,transaction,exportList} from './lib/core.mjs';
const a=args();if(a.help){console.log('tracker.mjs [--rebuild] [--history] [--id ID --resolve-duplicate reason]');process.exit(0);}
if(a.history){const workbook=path.join(root,'求职Dashboard.xlsx');const python=process.env.CAREER_PYTHON||path.join(process.env.USERPROFILE,'.cache/codex-runtimes/codex-primary-runtime/dependencies/python/python.exe');const p=spawnSync(python,[path.join(root,'.career-os/tools/lib/history.py'),workbook],{encoding:'utf8',maxBuffer:8e6});if(p.status!==0)throw Error(p.stderr);const keys=JSON.parse(p.stdout).map(normalizeUrl).filter(Boolean);const legacy=path.join(root,'.career-os/applications/intake');for(const f of await fs.readdir(legacy).catch(()=>[])){if(f.endsWith('.json')){const j=await read(path.join(legacy,f));if(j.url)keys.push(normalizeUrl(j.url));}}await write(path.join(home,'history-keys.json'),{keys:[...new Set(keys)],readAt:new Date().toISOString(),source:'Read-only Excel + earlier intake; known application is not proof of submission'});await transaction(s=>{for(const j of s.jobs)if(keys.includes(j.key))j.state='known-application';});}
if(a['resolve-duplicate']){if(!a.id||typeof a['resolve-duplicate']!=='string')throw Error('ID and reason required');await transaction(s=>{const j=s.jobs.find(x=>x.id===a.id);if(!j)throw Error('Unknown ID');j.duplicateResolution={reason:a['resolve-duplicate'],at:new Date().toISOString()};j.possibleDuplicates=[];j.state='discovered';});}
await exportList();await fs.mkdir(home,{recursive:true});const s=await read(path.join(home,'leads.json'),{jobs:[]});const db=new DatabaseSync(path.join(home,'tracker.sqlite'));try{db.exec('BEGIN; CREATE TABLE IF NOT EXISTS jobs (id TEXT PRIMARY KEY, company TEXT, role TEXT, url TEXT UNIQUE, state TEXT, priority INTEGER, output TEXT, updated TEXT); DELETE FROM jobs;');const insert=db.prepare('INSERT INTO jobs VALUES(?,?,?,?,?,?,?,?)');for(const j of s.jobs)insert.run(j.id,j.company||'',j.title||'',j.url,j.state,j.priority??null,j.output||'',j.lastSeenAt);db.exec('COMMIT');const rows=db.prepare(a.id?'SELECT * FROM jobs WHERE id=?':'SELECT * FROM jobs ORDER BY priority DESC, updated DESC');console.log(JSON.stringify(a.id?rows.all(a.id):rows.all(),null,2));}finally{db.close();}
