import fs from 'node:fs/promises';
import path from 'node:path';
import {args} from './runtime.mjs';
import {listing,posting} from './lib/listings.mjs';
import wttj from '../vendor/career-ops/wttj.mjs';
import {home,config,request,capture,transaction,add,write,exportList,read} from './lib/core.mjs';
const a=args();if(a.help){console.log('scan.mjs [--config .useless-linkedin/portals.yml] [--portal NAME] [--no-browser] [--import FILE] [--listing-capture FILE]');process.exit(0);}
const c=await config(a.config);const report={startedAt:new Date().toISOString(),portals:[],added:[],duplicates:[],searchRequests:[],bounded:true};
const norm=s=>String(s||'').normalize('NFD').replace(/\p{M}/gu,'').toLowerCase();
const match=j=>{const t=norm(j.title);return (c.include_keywords||[]).some(k=>t.includes(norm(k)))&&(c.role_keywords||[]).some(k=>t.includes(norm(k)))&&!(c.exclude_keywords||[]).some(k=>t.includes(norm(k)));};
let browserCaptures=a['listing-capture']?JSON.parse(await fs.readFile(a['listing-capture'],'utf8')):[];if(!Array.isArray(browserCaptures))browserCaptures=[browserCaptures];for(const x of browserCaptures){if(x.kind!=='listing'||!x.url||!Number.isFinite(Date.parse(x.capturedAt))||Math.abs(Date.now()-Date.parse(x.capturedAt))>86400000||typeof x.bodyText!=='string'||!Array.isArray(x.links)||x.links.some(l=>!l.title||!x.bodyText.includes(l.title)))throw Error('Listing capture requires recent observed page titles and links');}
let imported=a.import?JSON.parse(await fs.readFile(a.import,'utf8')):[];if(!Array.isArray(imported))throw Error('Import expects [{url,title,company,portal,location}]');
for(const portal of c.portals.filter(p=>p.enabled&&(!a.portal||p.name===a.portal))){const log={name:portal.name,attempts:[],found:0,filtered:0};let jobs=[];
 if(!a['import-only']&&portal.provider==='wttj'){try{jobs=await wttj.fetch(portal,{fetchText:async(u,o)=>{const r=await request(u,o);if(r.status!==200)throw Error(`HTTP ${r.status}`);return r.body;},fetchJson:async(u,o)=>{const r=await request(u,o);if(r.status!==200)throw Error(`HTTP ${r.status}`);return JSON.parse(r.body);}});log.attempts.push({layer:'API',count:jobs.length});}catch(e){log.attempts.push({layer:'API',error:e.message});}}
 if(!a['import-only']&&portal.api_url){try{const token=portal.api_token_env?process.env[portal.api_token_env]:null;if(portal.api_token_env&&!token)throw Error('API credential missing');const r=await request(portal.api_url,{headers:token?{Authorization:`Bearer ${token}`}:{}});if(r.status!==200)throw Error(`HTTP ${r.status}`);const body=JSON.parse(r.body);const rows=Array.isArray(body)?body:body.jobs;if(!Array.isArray(rows))throw Error('Configured API must expose jobs array; adapt official API response before import');jobs.push(...rows);log.attempts.push({layer:'API',count:rows.length});}catch(e){log.attempts.push({layer:'API',error:e.message});}}
 if(!a['import-only']&&!jobs.some(match)&&portal.search_url){for(const query of (portal.queries||c.queries||[]).slice(0,3)){const url=portal.search_url.replace('{query}',encodeURIComponent(query));const observed=browserCaptures.find(x=>x.url===url);const page=observed?{jobs:observed.links.map(l=>posting(l,portal,observed.url)).filter(Boolean).filter(match),attempts:[{layer:'AgentBrowser',url,status:200,observedAt:observed.capturedAt}]}:await listing(url,{portal,match,browser:!a['no-browser']});log.attempts.push(...page.attempts);jobs.push(...page.jobs);if(!page.jobs.length)report.searchRequests.push({portal:portal.name,query:`site:${portal.search_domain||new URL(url).hostname} ${query} Paris France`,url,reason:'No usable public listing; Agent WebSearch required',completed:false});}}
 jobs.push(...imported.filter(j=>j.portal===portal.name).flatMap(j=>{const p=posting(j,portal,portal.search_url||j.url);return p?[{...j,...p}]:[];}));log.found=jobs.length;const seen=new Set();for(const j of jobs){if(j.kind==='predicted-recruiter'||j.source==='recruteurs_lba')continue;if(!j.url||!match(j)||seen.has(j.url))continue;seen.add(j.url);if(log.filtered>=(c.max_results_per_portal||40))break;log.filtered++;const result=await transaction(s=>add(s,{...j,portal:portal.name}));report[result.duplicate?'duplicates':'added'].push(result);}
 log.status=log.filtered?'results':a['import-only']?'not-imported':'needs-search';report.portals.push(log);
}
report.finishedAt=new Date().toISOString();await transaction(s=>{s.scans.push(report);s.scans=s.scans.slice(-100);});await write(path.join(home,'last-scan.json'),report);if(!a['import-only']){const previous=await read(path.join(home,'search-queue.json'),[]),handled=new Set(report.portals.flatMap(p=>p.attempts.map(x=>x.url).filter(Boolean))),apiSuccess=new Set(report.portals.filter(p=>p.filtered&&p.attempts.some(x=>x.layer==='API'&&!x.error)).map(p=>p.name));const queue=[...new Map([...previous.filter(x=>!handled.has(x.url)&&!apiSuccess.has(x.portal)),...report.searchRequests].map(x=>[x.portal+'|'+x.query,x])).values()];await write(path.join(home,'search-queue.json'),queue);await write(path.join(home,'scan-agent-task.md'),queue.some(x=>!x.completed)?'Read search-queue.json. For each pending query, open the public listing in IAB. Collect visible posting titles and links (Indeed sj_ card IDs give /viewjob?jk=ID). Save a recent kind=listing capture with requested url, pageUrl, capturedAt, bodyText containing the observed titles, and links[{url,title}]. Run scan --listing-capture FILE --no-browser. If the browser is blocked, use Agent WebSearch and import discovered detail links with --import FILE --import-only. Keep discovery separate from full-JD liveness; do not submit or upload. See tools/README.md.':'No pending listing fallback.');}await exportList();console.log(JSON.stringify(report,null,2));
