import fs from 'node:fs/promises';
import path from 'node:path';
import {spawnSync} from 'node:child_process';
import {DatabaseSync} from 'node:sqlite';
import {root,args} from './runtime.mjs';
import {home,read,write,normalizeUrl,transaction,exportList} from './lib/core.mjs';
import {openDashboard} from './lib/dashboard-db.mjs';
const a=args();if(a.help){console.log('tracker.mjs [--rebuild] [--history] [--id ID --resolve-duplicate reason]');process.exit(0);}
if(a.history){const db=openDashboard(root);let rows;try{rows=db.prepare("SELECT id,job_url,source_sheet,source_row FROM applications WHERE job_url<>''").all();}finally{db.close();}const entries=rows.map(x=>({id:x.id,url:x.job_url,sheet:x.source_sheet,row:x.source_row,key:normalizeUrl(x.job_url)})).filter(x=>x.key);await write(path.join(home,'history-keys.json'),{entries,readAt:new Date().toISOString(),source:'Dashboard database; a history match is not proof of submission'});const byKey=new Map(entries.map(x=>[x.key,x]));await transaction(s=>{for(const j of s.jobs){const match=byKey.get(j.key);j.historyMatch=Boolean(match);j.historyEvidence=match?{source:'dashboard-db',recordId:match.id,sheet:match.sheet,row:match.row,url:match.url}:null;}});}
if(a['resolve-duplicate']){if(!a.id||typeof a['resolve-duplicate']!=='string')throw Error('ID and reason required');await transaction(s=>{const j=s.jobs.find(x=>x.id===a.id);if(!j)throw Error('Unknown ID');if(!['duplicate-review','possible-duplicate'].includes(j.state))throw Error('Duplicate resolution requires a duplicate review state');j.duplicateResolution={reason:a['resolve-duplicate'],at:new Date().toISOString()};j.possibleDuplicates=[];});}
await exportList();await fs.mkdir(home,{recursive:true});const s=await read(path.join(home,'leads.json'),{jobs:[]});const db=new DatabaseSync(path.join(home,'tracker.sqlite'));try{db.exec('BEGIN; CREATE TABLE IF NOT EXISTS jobs (id TEXT PRIMARY KEY, company TEXT, role TEXT, url TEXT UNIQUE, state TEXT, priority INTEGER, output TEXT, updated TEXT); DELETE FROM jobs;');const insert=db.prepare('INSERT INTO jobs VALUES(?,?,?,?,?,?,?,?)');for(const j of s.jobs)insert.run(j.id,j.company||'',j.title||'',j.url,j.state,j.priority??null,j.output||'',j.lastSeenAt);db.exec('COMMIT');const rows=db.prepare(a.id?'SELECT * FROM jobs WHERE id=?':'SELECT * FROM jobs ORDER BY priority DESC, updated DESC');console.log(JSON.stringify(a.id?rows.all(a.id):rows.all(),null,2));}finally{db.close();}
